routes/front.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Front\ShopComponent;
use App\Http\Controllers\Front\HomeController;
use \App\Http\Controllers\Front\Auth\SocialAuth;
use App\Http\Livewire\Front\ProductDetailComponent;
use App\Http\Controllers\Front\Account\MyShopController;
use App\Http\Controllers\Front\Account\BookingController;
use App\Http\Controllers\Front\Account\ProfileController;
use App\Http\Controllers\Front\Account\AdressesController;
use App\Http\Controllers\Front\Account\DashboardController;
use App\Http\Controllers\Front\PageController;
use App\Http\Controllers\Front\CartController;

/*
|--------------------------------------------------------------------------
| Front Routes
|--------------------------------------------------------------------------
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::post('/chercher', [HomeController::class,'filter'])->name('home.filter');

Route::get('/emprunter/tenus/{product}', ProductDetailComponent::class)->name('product.detail');
Route::get('/emprunter/{category?}', ShopComponent::class)->name('shop');
Route::get('/le-concept', [PageController::class, 'leConcept'])->name('le-concept');
Route::get('/faq', [PageController::class, 'faq'])->name('faq');
Route::get('/politique', [PageController::class,'politique'])->name('home.politique');

// Scoial Login
Route::get('/auth/redirect/{driver}', [SocialAuth::class, 'redirect'])->name('social.redirect');
Route::get('/auth/callback/{driver}', [SocialAuth::class, 'callback'])->name('social.callback');
Route::post('/auth/set-password', [SocialAuth::class, 'setPassword'])->name('social.set-password');

// Cart
Route::post('/panier/ajouter', [CartController::class,'add'])->name('addtocart');
Route::post('/panier/supprimer', [CartController::class,'delete'])->name('deletefromcart');
Route::get('/panier', [CartController::class,'show'])->name('showcart');
Route::match(['post','get'],'/panier/checkout',[CartController::class,'checkout'])->middleware(['auth', 'verified'])->name('checkout');
Route::post('/panier/enregistrer',[CartController::class,'save_order'])->middleware(['auth', 'verified'])->name('save_order');

Route::get('/videpanier',[CartController::class,'cart_flush'])->name('cartflush');


Route::group(['as' => 'account.', 'prefix' => 'mon-compte', 'middleware' => ['auth', 'verified']], function () {
    Route::get('/', [ProfileController::class, 'index'])->name('dashboard');

    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');

    Route::get('/adresses', [AdressesController::class, 'index'])->name('addresses');
    Route::get('/adresses/ajouter', [AdressesController::class, 'add'])->name('address.add');
    Route::post('/adresses/enregistrer',[AdressesController::class, 'store'])->name('address.store');
    Route::get('/adresses/{id}', [AdressesController::class, 'edit'])->name('address.edit');
    Route::post('/adresses/{id}', [AdressesController::class, 'update'])->name('address.update');
    Route::delete('/adresses/supprimer/{id}', [AdressesController::class, 'destroy'])->name('address.destroy');
    Route::get('/historique-des-achats', [DashboardController::class, 'orderHistory'])->name('order.history');
    Route::get('/moyens-de-paiement', [DashboardController::class, 'paymentMethods'])->name('payment.methods');


    Route::get('/ma-boutique', [MyShopController::class, 'index'])->name('my-shop');
    Route::get('/ma-boutique/ajouter-produit', [MyShopController::class, 'add_product'])->name('my-shop.add_product');
    Route::post('/ma-boutique/enregistrer-produit', [MyShopController::class, 'store_product'])->name('my-shop.store_product');
    Route::get('/ma-boutique/supprimer-produit/{id}', [MyShopController::class, 'delete_product'])->name('my-shop.delete_product');
    Route::get('/ma-boutique/mes-commissions', [MyShopController::class , 'my_commissions'])->name('my-shop.my-commissions');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('/', function () {
//    return view('welcome');
//});
//
//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth'])->name('dashboard');


/*
 * Frontend Routes
 */
Route::group(['as' => 'front.'], function () {
    require __DIR__.'/front.php';
});
require __DIR__ . '/auth.front.php';



/*
 * Backend Routes
 *
 * These routes can only be accessed by users with type `admin`
 */
Route::group(['prefix' => 'administrator', 'as' => 'admin.', 'middleware' => 'auth:administrator'], function () {
    require __DIR__.'/administrator.php';
});
require __DIR__ . '/auth.administrator.php';

app/Http/Controllers/Administrator/AdminController.php
<?php

namespace App\Http\Controllers\Administrator;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class AdminController extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Administrator/AttributeValuesController.php
<?php

namespace App\Http\Controllers\Administrator;

use App\Models\AttributeValues;
use App\Http\Controllers\Controller;
use App\Models\Attribute;
use Illuminate\Http\Request;

class AttributeValuesController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Attribute $attribute)
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Attribute $attribute)
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,Attribute $attribute)
    {
        $validated = $request->validate([
            'value' => 'required'
        ]);
        

        $attribute->values()->create($validated);


        return redirect()->route('admin.attributes.show',$attribute);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id,Attribute $attribute)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id,Attribute $attribute)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id,Attribute $attribute)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Attribute $attribute, AttributeValues $attribute_value)
    {
        $attribute_value->delete();

        return redirect()->route('admin.attributes.show',$attribute);
    }
}

app/Http/Controllers/Administrator/AttributesController.php
<?php

namespace App\Http\Controllers\Administrator;

use App\Models\Attribute;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AttributesController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('administrator.attributes.list',['attributes'=>Attribute::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('administrator.attributes.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required'
        ]);


        Attribute::create($validated);

        return redirect()->route('admin.attributes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Attribute $attribute
     * @return \Illuminate\Http\Response
     */
    public function show(Attribute $attribute)
    {
        return view('administrator.attributes.values',compact('attribute'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Attribute  $attribute
     * @return \Illuminate\Http\Response
     */
    public function edit(Attribute $attribute)
    {
        return view('administrator.attributes.edit',compact('attribute'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Attribute  $attribute
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Attribute $attribute)
    {
        $validated = $request->validate([
            'name' => 'required'
        ]);


        $attribute->update($validated);

        return redirect()->route('admin.attributes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Attribute  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Attribute $attribute)
    {
        $attribute->delete();

        return redirect()->route('admin.attributes.index');
    }
}

app/Http/Controllers/Administrator/BookingsController.php
<?php

namespace App\Http\Controllers\Administrator;

use Carbon\Carbon;
use App\Models\User;
use App\Models\Booking;
use App\Models\Product;
use App\Models\Commission;
use App\Models\StatusEvent;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Models\BookingStatusEvent;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Notifications\BookingStatusNotification;
use Database\Seeders\StatusEventSeeder;

class BookingsController extends AdminController
{
    public function index(Request $request)
    {
        $filterCode = $request->input('code');
        $filterProduct = $request->input('product_name');
        $filterUser = $request->input('user');
        $filterStatus = $request->input('status');
        $filterSdate = ($request->input('sdate') != null) ? Carbon::createFromFormat(
            'd/m/Y',
            $request->input('sdate')
        )->format('Y-m-d') : null;

        $collection = Booking::query();

        $collection->with([
            'products',
            'user',
            'currentStatus'
        ]);

        ////// /* Filter by code */
        $collection->when($filterCode, function ($collection, $filterCode) {
            return $collection->whereRaw("UPPER(code) LIKE '%". strtoupper($filterCode)."%'");
        });

        ////// /* Filter by product name */
        $collection->when($filterProduct, function ($collection, $filterProduct) {
            return $collection->where(
                function ($query) use ($filterProduct) {
                    $query->whereHas('products', function ($query) use ($filterProduct) {
                        $query->whereRaw("UPPER(name) LIKE '%". strtoupper($filterProduct)."%'");
                    });
                }

            );
        });

        ////// /* Filter by user */
        $collection->when($filterUser, function ($collection, $filterUser) {
            return $collection->where('user_id', '=', $filterUser);
        });

        ////// /* Filter by status */
        $collection->when($filterStatus, function ($collection, $filterStatus) {
            return $collection->where('status_event_id', '=', $filterStatus);
        });

        ////// /* Filter by start date */
        $collection->when($filterSdate, function ($collection, $filterSdate) {
            return $collection->where('start_date', '=', $filterSdate);
        });

        $bookings = $collection->orderBy('id')->paginate(2);

        $users = User::orderBy('name')->get();
        $status = StatusEvent::orderBy('id')->get();

        return view('administrator.bookings.list', compact('bookings', 'users', 'status'));
    }


    public function details($id)
    {
        $booking = Booking::with([
            'user',
            'deliveryAddress',
            'currentStatus',
            'status' => function ($query) {
                return $query->orderBy('created_at', 'DESC');
            }
        ])->findOrFail($id);

        $status = @$booking->currentStatus ?? '';

        $status_name = $status->name;
        $badge_class = '';


        $old_status = $booking->status;
        $archived = false;
        if($status->id === StatusEvent::STATUSES['canceled'] || $status->id === StatusEvent::STATUSES['ended']){
            $archived = true;
        }

        $status_events = StatusEvent::where('id', '>', $status->id)->get();
        return view('administrator.bookings.details', compact('booking', 'badge_class', 'status_name', 'status_events', 'old_status', 'archived'));
    }


    public function change_status(Request $request)
    {

        $validated = $request->validate([
            'status_event_id' => 'required',
            'booking_id' => 'required'
        ]);

        BookingStatusEvent::create($request->all());

        $booking = Booking::with('user', 'items', 'products')->findOrFail($request->input('booking_id'));



        //Customer notification
        //$notification = $booking->generateStatusNotification();
        $user = $booking->user;
        $user->notify(new BookingStatusNotification($booking));

        return redirect()->route('admin.bookings.details', $request->input('booking_id'));
    }


    public function payment_recieved(Request $request)
    {

        $validated = $request->validateWithBag('payment', [
            'payment_note' => 'required',
            'booking_id' => 'required'
        ]);

        $booking = Booking::findOrFail($request->input('booking_id'));
        $booking->payment_recieved = 1;
        $payment_date = Carbon::now()->format('d/m/Y H:i');
        $booking->payment_note = 'Date du paiement : ' . $payment_date . " <br> <b>Commentaire : </b>" . $request->input('payment_note');

        $booking->status_event_id = StatusEvent::STATUSES['confirmed'];

        $booking->update();

        $user = $booking->user;
        $user->notify(new BookingStatusNotification($booking));

        /* Add commission to the owner */
        foreach ($booking->items as $item) {
            $product = Product::findOrFail($item->product_id);
            $owner = User::findOrFail($product->user_id);

            $amount = round(($item->price * config('app.commission')), 1 );

            $commission = Commission::create([
                'user_id' => $owner->id,
                'booking_id' => $booking->id,
                'status' => "1",
                'amount' => $amount
            ]);
        }
        return redirect()->route('admin.bookings.details', $booking);
    }

    public function deposit_refunded(Request $request)
    {

        $booking = Booking::findOrFail($request->input('booking_id'));
        $booking->deposit_refunded = 1;
        $booking->update();

        return redirect()->route('admin.bookings.details', $booking);
    }
}

app/Http/Controllers/Administrator/CustomersController.php
<?php

namespace App\Http\Controllers\Administrator;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;

class CustomersController extends AdminController
{
    public function index(Request $request){

        $filterName = $request->input('name');
        $filterEmail = $request->input('email');

        $collection = User::query();

        $collection->withCount([
            'products',
            'bookings'
        ]);

        ////// /* Filter by name */
        $collection->when($filterName, function ($collection, $filterName) {
            return $collection->where('name','like','%'.$filterName.'%');
        });

        ////// /* Filter by email */
        $collection->when($filterEmail, function ($collection, $filterEmail) {
            return $collection->where('email','like','%'.$filterEmail.'%');
        });

        $customers = $collection->orderBy('created_at','ASC')->paginate(25);

        return view('administrator.customers.list', compact('customers'));
    }


    public function details($id){

        $customer = User::with([
            'products',
            'bookings',
            'deliveryAddresses'
            ])->findOrFail($id);

        $bookings   = $customer->bookings;
        $products   = $customer->products;
        $addresses  = $customer->deliveryAddresses;

        return view('administrator.customers.details',compact('customer','bookings','products','addresses'));
    }
}

resources/views/administrator/products/add.blade.php
@extends('administrator.layouts.app')

@section('css')

@endsection

@section('content')

    <div class="container-fluid">

        <div class="card">


            <form class="form-horizontal" action="{{ route('admin.products.store') }}" method="post">

                @csrf

                <div class="d-flex justify-content-between card-header">
                    <div>
                        <h4 class="card-title mb-0">Ajouter un produit</h4>

                    </div>

                </div>
                <div class="card-body">

                    <div class="form-group row mb-3">
                        <label class="col-md-3 col-form-label" for="name">Nom</label>
                        <div class="col-md-9">
                            <input
                                class="form-control  @error('name') is-invalid @enderror"
                                id="name"
                                type="text"
                                name="name"
                                required
                                value="{{ old('name') }}"
                                autocomplete="text">
                            @error('name')
                            <div class="text-danger p-1 small">{{ $message }}</div>
                            @enderror

                        </div>
                    </div>
                    <div class="form-group row mb-3">
                        <label class="col-md-3 col-form-label" for="name">Slug (Url du produit)</label>
                        <div class="col-md-9">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">{{ route('front.shop') }}/</span>
                                </div>
                                <input type="text" value="{{ old('slug') }}" name="slug" id="slug" class="form-control @error('slug') is-invalid @enderror" placeholder="slug" required autocomplete="off">
                            </div>
                            @error('slug')
                            <div class="text-danger p-1 small">{{ $message }}</div>
                            @enderror

                        </div>
                    </div>
                    <div class="form-group row mb-3">
                        <label class="col-md-3 col-form-label" for="user">Marque</label>
                        <div class="col-md-6">
                            <select name="brand"
                            class="form-control @error('brand') is-invalid @enderror">
                            <option value="">Selectionnez...</option>
                                @foreach($brands as $brand)

                                    <option
                                    @if(old('brand')==$brand->id) selected="selected" @endif
                                        value="{{ $brand->id }}">
                                            {{ $brand->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row  mb-3">
                        <label class="col-md-3 col-form-label" for="rent_price">Prix location</label>
                        <div class="col-md-3 input-group">
                            <input
                                class="form-control  @error('rent_price') is-invalid @enderror"
                                id="rent_price"
                                type="text"
                                name="rent_price"
                                required
                                value="{{ old('rent_price') }}">
                                <div class="input-group-append"><span class="input-group-text">DT</span></div>
                        </div>
                        <label class="col-md-3 col-form-label text-right" for="value_price">Prix Achat</label>
                        <div class="col-md-3 input-group">
                            <input
                                class="form-control  @error('value_price') is-invalid @enderror"
                                id="value_price"
                                type="text"
                                name="value_price"
                                value="{{ old('value_price') }}"
                                required>
                            <div class="input-group-append"><span class="input-group-text">DT</span></div>
                        </div>

                    </div>

                    @include('administrator.partials.attributes_fields')

                    <div class="form-group row mb-3">
                        <label class="col-md-3 col-form-label" for="name">Style</label>
                        <div class="col-md-9">
                            <textarea
                                class="form-control  @error('style_description') is-invalid @enderror"
                                id="style_description"
                                name="style_description">{{ old('style_description') }}</textarea>
                        </div>
                    </div>
                    <div class="form-group row mb-3">
                        <label class="col-md-3 col-form-label" for="composition_description">Composition</label>
                        <div class="col-md-9">
                            <textarea
                                class="form-control  @error('composition_description') is-invalid @enderror"
                                id="composition_description"
                                name="composition_description">{{ old('composition_description') }}</textarea>
                        </div>
                    </div>
                    <div class="form-group row mb-3">
                        <label class="col-md-3 col-form-label" for="size_description">Taille et mesure</label>
                        <div class="col-md-9">
                            <textarea
                                class="form-control  @error('size_description') is-invalid @enderror"
                                id="size_description"
                                name="size_description">{{ old('size_description') }}</textarea>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="is_online">Mettre en ligne</label>
                        <div class="col-md-9">

                            <label class="c-switch c-switch-label c-switch-pill c-switch-success">
                                <input id="is_online" class="c-switch-input" name="is_online" value="1" type="checkbox" @if(old('is_online' ) == true) checked="" @endif><span class="c-switch-slider" data-checked="On" data-unchecked="Off"></span>
                            </label>
                        </div>
                    </div>

                    <input type="hidden" name="category" value="{{$selected_category }}"/>
                    <input type="hidden" name="user" value="{{ $selected_user }}"/>
                    @if(old('submited_id'))
                    <input type="hidden" name="submited_id" value="{{ old('submited_id') }}"/>
                    @endif
                </div>
                <div class="card-footer ">
                    <button class="btn btn btn-primary" type="submit"> Enregistrer</button>
                    <button class="btn btn btn-secondary" type="reset"
                        onclick="window.location.href='{{ route('admin.products.index') }}'"> Annuler</button>
                </div>

            </form>



        </div>

    </div>

@endsection

@section('javascript')
    <script type="text/javascript" src="{{ asset('admin_assets/js/jquery.js') }}"></script>
    <script>
        $(document).ready(function () {
            String.prototype.slugify = function (separator = "-") {
                return this
                    .toString()
                    .normalize('NFD')                   // split an accented letter in the base letter and the acent
                    .replace(/[\u0300-\u036f]/g, '')   // remove all previously split accents
                    .toLowerCase()
                    .trim()
                    .replace(/[^a-z0-9 ]/g, '')   // remove all chars not letters, numbers and spaces (to be replaced)
                    .replace(/\s+/g, separator);
            };

            $('#name').on('change', function () {
                $('#slug').val($(this).val().slugify())
            })


        })
    </script>


@endsection

resources/views/administrator/products/product_images_gallery_response.blade.php
    <div class="d-flex flex-row" id="sortable">
@forelse($images as $image)
        <div class="card  pl-0 pr-0 mx-2" id="sortable_{{ $image->id}}">

            <img class="bd-placeholder-img card-img-top" width="120" height="180" src="{{ asset('storage/imgs/gallery_thumb_'.$image->file_name) }}" />

            <div class="card-body">
                <a class="delete_img"  role="button">
                    <input type="hidden" value="{{ $image->id}}" class="image_id" />
                    <svg class="c-icon">
                      <use xlink:href="{{ asset('admin_assets/assets/icons/coreui/free-symbol-defs.svg#cui-trash')}}"></use>
                  </svg>
                </a>

            <span class="float-right">#{{ $image->order}}</span>
            </div>
        </div>
@empty
    <center><i>Aucune image</i></center>
@endforelse
    </div>

resources/views/administrator/products/show.blade.php
@extends('administrator.layouts.app')

@section('css')

@endsection

@section('content')


    <div class="container-fluid">
        <p class="h3">{{ $product->name }} </p>
        <small><a href="#" target="blank">Voir en ligne</a></small>
        <hr>
        <div class="nav-tabs-boxed">
            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#home-1" role="tab"
                        aria-controls="home" aria-selected="true">General</a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#profile-1" role="tab"
                        aria-controls="profile" aria-selected="false">Images <span class="badge bg-secondary ml-1" id="image_count">0</span></a></li>
                <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#messages-1" role="tab"
                        aria-controls="messages" aria-selected="false">Historique commande</a></li>
            </ul>
            <div class="tab-content ">
                <div class="tab-pane active" id="home-1" role="tabpanel">

                    @include('administrator.partials.products.product_showtab_general')  

                </div>
                <div class="tab-pane" id="profile-1" role="tabpanel">
                    @include('administrator.partials.products.product_showtab_imgs')
                </div>
                <div class="tab-pane" id="messages-1" role="tabpanel">Historique des ventes, mise a jour....</div>
            </div>
        </div>
    </div>

@endsection

@section('javascript')


@endsection