routes/front.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Front\ShopComponent;
use App\Http\Controllers\Front\HomeController;
use \App\Http\Controllers\Front\Auth\SocialAuth;
use App\Http\Livewire\Front\ProductDetailComponent;
use App\Http\Controllers\Front\Account\MyShopController;
use App\Http\Controllers\Front\Account\BookingController;
use App\Http\Controllers\Front\Account\ProfileController;
use App\Http\Controllers\Front\Account\AdressesController;
use App\Http\Controllers\Front\Account\DashboardController;
use App\Http\Controllers\Front\PageController;
use App\Http\Controllers\Front\CartController;

/*
|--------------------------------------------------------------------------
| Front Routes
|--------------------------------------------------------------------------
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::post('/chercher', [HomeController::class,'filter'])->name('home.filter');

Route::get('/emprunter/tenus/{product}', ProductDetailComponent::class)->name('product.detail');
Route::get('/emprunter/{category?}', ShopComponent::class)->name('shop');
Route::get('/le-concept', [PageController::class, 'leConcept'])->name('le-concept');
Route::get('/faq', [PageController::class, 'faq'])->name('faq');
Route::get('/politique', [PageController::class,'politique'])->name('home.politique');

// Scoial Login
Route::get('/auth/redirect/{driver}', [SocialAuth::class, 'redirect'])->name('social.redirect');
Route::get('/auth/callback/{driver}', [SocialAuth::class, 'callback'])->name('social.callback');
Route::post('/auth/set-password', [SocialAuth::class, 'setPassword'])->name('social.set-password');

// Cart
Route::post('/panier/ajouter', [CartController::class,'add'])->name('addtocart');
Route::post('/panier/supprimer', [CartController::class,'delete'])->name('deletefromcart');
Route::get('/panier', [CartController::class,'show'])->name('showcart');
Route::match(['post','get'],'/panier/checkout',[CartController::class,'checkout'])->middleware(['auth', 'verified'])->name('checkout');
Route::post('/panier/enregistrer',[CartController::class,'save_order'])->middleware(['auth', 'verified'])->name('save_order');

Route::get('/videpanier',[CartController::class,'cart_flush'])->name('cartflush');


Route::group(['as' => 'account.', 'prefix' => 'mon-compte', 'middleware' => ['auth', 'verified']], function () {
    Route::get('/', [ProfileController::class, 'index'])->name('dashboard');

    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');

    Route::get('/adresses', [AdressesController::class, 'index'])->name('addresses');
    Route::get('/adresses/ajouter', [AdressesController::class, 'add'])->name('address.add');
    Route::post('/adresses/enregistrer',[AdressesController::class, 'store'])->name('address.store');
    Route::get('/adresses/{id}', [AdressesController::class, 'edit'])->name('address.edit');
    Route::post('/adresses/{id}', [AdressesController::class, 'update'])->name('address.update');
    Route::delete('/adresses/supprimer/{id}', [AdressesController::class, 'destroy'])->name('address.destroy');
    Route::get('/historique-des-achats', [DashboardController::class, 'orderHistory'])->name('order.history');
    Route::get('/moyens-de-paiement', [DashboardController::class, 'paymentMethods'])->name('payment.methods');


    Route::get('/ma-boutique', [MyShopController::class, 'index'])->name('my-shop');
    Route::get('/ma-boutique/ajouter-produit', [MyShopController::class, 'add_product'])->name('my-shop.add_product');
    Route::post('/ma-boutique/enregistrer-produit', [MyShopController::class, 'store_product'])->name('my-shop.store_product');
    Route::get('/ma-boutique/supprimer-produit/{id}', [MyShopController::class, 'delete_product'])->name('my-shop.delete_product');
    Route::get('/ma-boutique/mes-commissions', [MyShopController::class , 'my_commissions'])->name('my-shop.my-commissions');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('/', function () {
//    return view('welcome');
//});
//
//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth'])->name('dashboard');


/*
 * Frontend Routes
 */
Route::group(['as' => 'front.'], function () {
    require __DIR__.'/front.php';
});
require __DIR__ . '/auth.front.php';



/*
 * Backend Routes
 *
 * These routes can only be accessed by users with type `admin`
 */
Route::group(['prefix' => 'administrator', 'as' => 'admin.', 'middleware' => 'auth:administrator'], function () {
    require __DIR__.'/administrator.php';
});
require __DIR__ . '/auth.administrator.php';

app/Models/Booking.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Query\Builder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Booking extends Model
{
    use HasFactory;

    protected $table = 'bookings';


    protected $fillable = [
        'code', 'user_id', 'delivery_address_id',
        'status_event_id', 'start_date', 'end_date', 'price',
        'deposit', 'note', 'payment_note', 'payment_recieved', 'deposit_refunded'
    ];


    protected $dates = [
        'end_date',
        'start_date',
    ];

    /**
     * Prepare a date for array / JSON serialization.
     *
     * @param  \DateTimeInterface  $date
     * @return string
     */
    protected function serializeDate(\DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }



    public function status()
    {
        return $this->belongsToMany(StatusEvent::class, 'booking_status_events')->withPivot('details', 'created_at');
    }


    public function currentStatus()
    {
        return $this->belongsTo(StatusEvent::class, 'status_event_id');
    }


    public function user()
    {
        return $this->belongsTo(User::class);
    }


    public function products()
    {
        return $this->belongsToMany(Product::class, 'booking_items');
    }

    public function items()
    {
        return $this->hasMany(BookingItems::class);
    }

    public function deliveryAddress()
    {

        return $this->belongsTo(DeliveryAddresses::class);
    }

    public function getPeriodAttribute()
    {
        return $this->start_date->diffInDays($this->end_date->addHours(24));

    }

    public function getTypeAttribute()
    {
        return $this->start_date->diffInDays($this->end_date->addHours(24)) > 2 ? 'Location' : 'Essayage';

    }

//    public function getEndDateAttribute($value){
//        return Carbon::parse($value)->addHours(24);
//    }

    public function getBadgeClassAttribute($value)
    {
            return ' status-'.$this->status_event_id;

    }


    public function generateStatusNotification()
    {

        $subject = 'Votre commande #' . $this->code . ' ';

        $msg = 'Bonjour ' . $this->user->name . ',<br>';

        $products_list = '<ul>';
        foreach ($this->products as $product) {
            $products_list .= '<li><b>' . $product->name . '</b></li>';
        }
        $products_list .= '</ul>';


        switch ($this->status_event_id) {

            case '1': //Commande pending
                $subject .= ' a été enregistrée';
                $msg .= '<br> Vous serez notifier lorsque elle sera confirmée';
                break;
            case '2': //Commande confirmé
                $subject .= ' a été confirmée';
                $msg .= '<br> Vous serez notifier lorsque elle sera expédiée';
                break;

            case '3': //Commande livrée
                $subject .= ' a été livrée';
                $msg .= "<br> Profitez-en
                                <br>N'oublier pas que la date de retour est
                                le :" . Str::ucfirst($this->end_date->translatedFormat('l d/m/Y')) .
                    " avant 12h:00, nous comptons sur votre compréhonsion";
                break;

            case '4': //Commande à retournée
                $subject = 'Notification pour retour du produit que vous avez commandé';
                $msg .= 'Suite à la fin de la période de location, Merci de bien vouloir nous retourner :'
                    . $products_list
                    . 'Veuillez noter que la date de retourn est le :<b>' . Str::ucfirst($this->end_date->translatedFormat('l d/m/Y')) .
                    '</b> avant 12h:00 , nous comptons sur votre compréhonsion';
                break;
            case '5': //Commande retournée
                $subject = 'Notification du retour du produit';
                $msg .= 'Nous avons bien reçu le(s) article(s) :' . $products_list
                    . 'On vous remercie pour votre collaboration.<br>'
                    . "N'hésitez pas à consulter notre catalogue pour d'autre commande.";
                break;
            case '6': //Commande annulée
                $subject .= ' a été annulée';
                $msg .= "<br> N'hésitez pas à nous contacter si vous voulez plus d'information.";
                break;
        }

        $notification = array(
            'subject' => $subject,
            'msg' => $msg
        );

        return $notification;
    }

    public static function getDeliveryByPeriod($from, $to = false, $booking = false)
    {
        $collection = Booking::query();

        $collection->with('items', 'user', 'deliveryAddress');
        $collection->where('status_event_id','=',StatusEvent::STATUSES['confirmed']);

        if ($to) {
            $collection->whereBetween('start_date', [$from, $to]);
        } else {
            $collection->whereDate('start_date', '=', $from);
        }


        if ($booking) {
            $collection->where('id', '=', $booking);
        }

        return $collection->get();

    }


    public static function getBookingsInRange($start_date, $end_date, $filterBy = false, $comparision)
    {
//        $collection = Booking::query();
//
//        $collection->with('items', 'user', 'deliveryAddress');
//        $collection->whereDate('start_date', '>=', $from);
//        $collection->whereDate('start_date', [$from, $to]);
//        return $collection->get();

        return Booking::query()
            ->with('items', 'user', 'deliveryAddress')
            ->where('status_event_id','<>',StatusEvent::STATUSES['canceled'])
            ->orWhereBetween('start_date', [$start_date,$end_date])
            ->orWhereBetween('end_date', [$start_date,$end_date])
//            ->where('status_event_id', '>=', StatusEvent::STATUSES['ended'])
            ->get();


    }

    public static function getReturnsByPeriod($from, $to, $group = false)
    {
        $collection = Booking::query();

        $collection->with('items', 'user')
            ->where('status_event_id',  StatusEvent::STATUSES['delivered'])
            ->where('payment_recieved', 1);

        if ($to) {
            $collection->whereBetween('end_date', [$from, $to]);
        } else {
            $collection->whereDate('end_date', '=', $from);
        }


        return $collection->get();

    }

    public static function getBookedProducts($start_date, $end_date, $product_id = false)
    {
        $query = DB::table('bookings')
            ->join('booking_items', 'bookings.id', '=', 'booking_items.booking_id')
            ->where('bookings.status_event_id','<>', StatusEvent::STATUSES['ended'])
            ->where('bookings.status_event_id','<>', StatusEvent::STATUSES['canceled'])
            ->where(function ($query) use ($end_date, $start_date) {
                $query->whereBetween('start_date',[$start_date,$end_date])
                    ->orWhereBetween('end_date',[$start_date,$end_date])
                    ->orWhereBetween(DB::raw("'" . $start_date . "'"), [DB::raw("`start_date`"), DB::raw("`end_date`")])
                    ->orWhereBetween(DB::raw("'" . $end_date . "'"), [DB::raw("`start_date`"), DB::raw("`end_date`")]);
            })
            ->select(['booking_items.product_id']);

        if ($product_id) {
            $query->where('booking_items.product_id', '=', $product_id);
        }

        $result = $query->get();

        $booked_products = array();

        foreach ($result as $r) {
            $booked_products[] = $r->product_id;
        }
        return $booked_products;
    }


    public static function getBookedDetailProducts($start_date, $end_date, $product_id = false)
    {
        $query = Booking::with(['items', 'products'])
            ->whereBetween('start_date',[$start_date,$end_date])
            ->whereBetween('end_date',[$start_date,$end_date])
            ->whereBetween(DB::raw("'" . $start_date . "'"), [DB::raw("`start_date`"), DB::raw("`end_date`")])
            ->orWhereBetween(DB::raw("'" . $end_date . "'"), [DB::raw("`start_date`"), DB::raw("`end_date`")])
            ->where('status_event_id', '>=', StatusEvent::STATUSES['ended']);
        if ($product_id) {
            $query->where('booking_items.product_id', '=', $product_id);
        }

        $result = $query->get();

        $booked_products = array();

        foreach ($result as $r) {
            $booked_products[] = $r;
        }

        return $booked_products;
    }


}

app/Http/Controllers/Administrator/AdminController.php
<?php

namespace App\Http\Controllers\Administrator;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class AdminController extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Administrator/AttributeValuesController.php
<?php

namespace App\Http\Controllers\Administrator;

use App\Models\AttributeValues;
use App\Http\Controllers\Controller;
use App\Models\Attribute;
use Illuminate\Http\Request;

class AttributeValuesController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Attribute $attribute)
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Attribute $attribute)
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,Attribute $attribute)
    {
        $validated = $request->validate([
            'value' => 'required'
        ]);
        

        $attribute->values()->create($validated);


        return redirect()->route('admin.attributes.show',$attribute);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id,Attribute $attribute)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id,Attribute $attribute)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id,Attribute $attribute)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Attribute $attribute, AttributeValues $attribute_value)
    {
        $attribute_value->delete();

        return redirect()->route('admin.attributes.show',$attribute);
    }
}

app/Http/Controllers/Administrator/CustomersController.php
<?php

namespace App\Http\Controllers\Administrator;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;

class CustomersController extends AdminController
{
    public function index(Request $request){

        $filterName = $request->input('name');
        $filterEmail = $request->input('email');

        $collection = User::query();

        $collection->withCount([
            'products',
            'bookings'
        ]);

        ////// /* Filter by name */
        $collection->when($filterName, function ($collection, $filterName) {
            return $collection->where('name','like','%'.$filterName.'%');
        });

        ////// /* Filter by email */
        $collection->when($filterEmail, function ($collection, $filterEmail) {
            return $collection->where('email','like','%'.$filterEmail.'%');
        });

        $customers = $collection->orderBy('created_at','ASC')->paginate(25);

        return view('administrator.customers.list', compact('customers'));
    }


    public function details($id){

        $customer = User::with([
            'products',
            'bookings',
            'deliveryAddresses'
            ])->findOrFail($id);

        $bookings   = $customer->bookings;
        $products   = $customer->products;
        $addresses  = $customer->deliveryAddresses;

        return view('administrator.customers.details',compact('customer','bookings','products','addresses'));
    }
}

resources/views/administrator/bookings/list.blade.php
@extends('administrator.layouts.app')

@section('css')

@endsection

@section('content')



    <div class="container-fluid">

        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between mb-3">
                    <div>
                        <h4 class="card-title mb-0">Commandes </h4>

                    </div>

                </div>

                <hr>
                <nav class="navbar navbar-light bg-light">
                    <form action="" method="GET">
                        @csrf
                        <div class="form-row">
                            <div class="col-1">
                                <input type="text" name='code' class="form-control" placeholder="Code"
                                    value="{{ request('code') }}">
                            </div>
                            <div class="col">
                                <input type="text" name='product_name' class="form-control" placeholder="Nom du produit"
                                    value="{{ request('product_name') }}">
                            </div>
                            <div class="col">
                                <select name="user" id="inputState" class="form-control">
                                    <option value="">Selectionnez un proprietaire</option>
                                    @foreach ($users as $user)
                                        <option value="{{ $user->id }}" @if (request('user') == $user->id) selected="selected" @endif>{{ $user->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col">
                                <select name="status" id="inputState" class="form-control">
                                    <option value="">Selectionnez un etat</option>
                                    @foreach ($status as $s)
                                        <option value="{{ $s->id }}" @if (request('status') == $s->id) selected="selected" @endif>{{ $s->name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col input-group date">
                                <input type="text" class="form-control" name="sdate" value="{{ request('sdate') }}"
                                    placeholder="Date debut" autocomplete="off"><span class="input-group-addon"><i
                                        class="glyphicon glyphicon-th"></i></span>
                            </div>
                            <div class="col">
                                <button type="submit" class="btn btn-primary mb-2" name="filter">Chercher</button>
                                <button type="reset" class="btn btn-secondary mb-2"
                                    onclick="window.location.href='{{ route('admin.bookings.index') }}'">Annuler</button>
                            </div>
                        </div>
                    </form>
                </nav>

                <table class="table table-sm table-responsive-sm table-striped">
                    <thead>
                        <tr>
                            <th>Code</th>
                            <th>Client</th>
                            <th>Produits</th>
                            <th>Periode</th>
                            <th>Etat</th>
                            <th>Statut du Paiment</th>
                            <th>Montant</th>
                            <th>Caution</th>
                            <th>Date de demande</th>
                        </tr>
                    </thead>
                    <tbody>

                        @forelse ($bookings as $booking)

                            <tr>

                                <td>
                                    <a href="{{ route('admin.bookings.details', $booking) }}">#{{ $booking->code }}</a>
                                </td>

                                <td>
                                    #{{ $booking->user_id }} {{ $booking->user->name }}
                                </td>
                                <td>
                                    <ul class="p-0">
                                        @foreach ($booking->products as $product)
                                            <li>{{ Str::limit($product->name, 20) }}</li>
                                        @endforeach
                                    </ul>
                                </td>
                                <td c>
                                    {{ $booking->start_date->format('Y-m-d') }}
                                    -
                                    {{ $booking->end_date->translatedFormat('Y-m-d') }}
                                    <br>
                                    {{$booking->start_date->diffForHumans()}} - Pour {{ $booking->start_date->diffInDays($booking->end_date->addHours(24)) }} Jours
                                </td>
                                <td>
                                    <span class="badge {{ $booking->badge_class }}">
                                        {{ $booking->currentStatus->name }}
                                    </span>
                                </td>

                                <td>
                                    @if ($booking->payment_recieved == 1)
                                        <span class="badge bg-success text-white">
                                            PAIEMENT RECU
                                        </span>
                                    @endif

                                    @if ($booking->deposit_refunded == 1)
                                        <span class="badge bg-primary text-white">
                                            CAUTION RENDU
                                        </span>
                                    @endif
                                </td>
                                <td>
                                    <strong>{{ $booking->price }} DT</strong>
                                </td>

                                <td>
                                    {{ $booking->deposit }} DT
                                </td>
                                <td class="small">
                                    {{ $booking->created_at }}
                                </td>

                            </tr>
                        @empty
                            <tr>
                                <td colspan="9">
                                    <center><i>Pas de données</i></center>
                                </td>
                            </tr>

                        @endforelse

                    </tbody>
                </table>

                {{ $bookings->withQueryString()->links() }}
            </div>
        </div>

    </div>

@endsection

@push('scripts')
    <link rel="stylesheet" href="{{ asset('admin_assets/bootstrap-datepicker/css/bootstrap-datepicker3.min.css') }}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="{{ asset('admin_assets/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('admin_assets/bootstrap-datepicker/locales/bootstrap-datepicker.fr.min.js') }}"></script>

    <script src="{{ asset('admin_assets/js/popper.min.js') }}"></script>
@endpush
@section('javascript')

    <script>
        jQuery(document).ready(function() {

            $('.input-group.date').datepicker({
                format: "dd/mm/yyyy",
                todayBtn: true,
                language: "fr",
                todayHighlight: true
            });

            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
@endsection