routes/front.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Front\ShopComponent;
use App\Http\Controllers\Front\HomeController;
use \App\Http\Controllers\Front\Auth\SocialAuth;
use App\Http\Livewire\Front\ProductDetailComponent;
use App\Http\Controllers\Front\Account\MyShopController;
use App\Http\Controllers\Front\Account\BookingController;
use App\Http\Controllers\Front\Account\ProfileController;
use App\Http\Controllers\Front\Account\AdressesController;
use App\Http\Controllers\Front\Account\DashboardController;
use App\Http\Controllers\Front\PageController;
use App\Http\Controllers\Front\CartController;

/*
|--------------------------------------------------------------------------
| Front Routes
|--------------------------------------------------------------------------
*/

Route::get('/', [HomeController::class, 'index'])->name('home');
Route::post('/chercher', [HomeController::class,'filter'])->name('home.filter');

Route::get('/emprunter/tenus/{product}', ProductDetailComponent::class)->name('product.detail');
Route::get('/emprunter/{category?}', ShopComponent::class)->name('shop');
Route::get('/le-concept', [PageController::class, 'leConcept'])->name('le-concept');
Route::get('/faq', [PageController::class, 'faq'])->name('faq');
Route::get('/politique', [PageController::class,'politique'])->name('home.politique');

// Scoial Login
Route::get('/auth/redirect/{driver}', [SocialAuth::class, 'redirect'])->name('social.redirect');
Route::get('/auth/callback/{driver}', [SocialAuth::class, 'callback'])->name('social.callback');
Route::post('/auth/set-password', [SocialAuth::class, 'setPassword'])->name('social.set-password');

// Cart
Route::post('/panier/ajouter', [CartController::class,'add'])->name('addtocart');
Route::post('/panier/supprimer', [CartController::class,'delete'])->name('deletefromcart');
Route::get('/panier', [CartController::class,'show'])->name('showcart');
Route::match(['post','get'],'/panier/checkout',[CartController::class,'checkout'])->middleware(['auth', 'verified'])->name('checkout');
Route::post('/panier/enregistrer',[CartController::class,'save_order'])->middleware(['auth', 'verified'])->name('save_order');

Route::get('/videpanier',[CartController::class,'cart_flush'])->name('cartflush');


Route::group(['as' => 'account.', 'prefix' => 'mon-compte', 'middleware' => ['auth', 'verified']], function () {
    Route::get('/', [ProfileController::class, 'index'])->name('dashboard');

    Route::get('/profile', [ProfileController::class, 'index'])->name('profile');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');

    Route::get('/adresses', [AdressesController::class, 'index'])->name('addresses');
    Route::get('/adresses/ajouter', [AdressesController::class, 'add'])->name('address.add');
    Route::post('/adresses/enregistrer',[AdressesController::class, 'store'])->name('address.store');
    Route::get('/adresses/{id}', [AdressesController::class, 'edit'])->name('address.edit');
    Route::post('/adresses/{id}', [AdressesController::class, 'update'])->name('address.update');
    Route::delete('/adresses/supprimer/{id}', [AdressesController::class, 'destroy'])->name('address.destroy');
    Route::get('/historique-des-achats', [DashboardController::class, 'orderHistory'])->name('order.history');
    Route::get('/moyens-de-paiement', [DashboardController::class, 'paymentMethods'])->name('payment.methods');


    Route::get('/ma-boutique', [MyShopController::class, 'index'])->name('my-shop');
    Route::get('/ma-boutique/ajouter-produit', [MyShopController::class, 'add_product'])->name('my-shop.add_product');
    Route::post('/ma-boutique/enregistrer-produit', [MyShopController::class, 'store_product'])->name('my-shop.store_product');
    Route::get('/ma-boutique/supprimer-produit/{id}', [MyShopController::class, 'delete_product'])->name('my-shop.delete_product');
    Route::get('/ma-boutique/mes-commissions', [MyShopController::class , 'my_commissions'])->name('my-shop.my-commissions');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('/', function () {
//    return view('welcome');
//});
//
//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth'])->name('dashboard');


/*
 * Frontend Routes
 */
Route::group(['as' => 'front.'], function () {
    require __DIR__.'/front.php';
});
require __DIR__ . '/auth.front.php';



/*
 * Backend Routes
 *
 * These routes can only be accessed by users with type `admin`
 */
Route::group(['prefix' => 'administrator', 'as' => 'admin.', 'middleware' => 'auth:administrator'], function () {
    require __DIR__.'/administrator.php';
});
require __DIR__ . '/auth.administrator.php';

app/Http/Controllers/Front/Account/AdressesController.php
<?php

namespace App\Http\Controllers\Front\Account;

use Illuminate\Http\Request;
use App\Models\DeliveryAddresses;
use App\Http\Controllers\Controller;
use App\Http\Requests\Front\AddressRequest;
use Illuminate\Support\Facades\Validator;


class AdressesController extends Controller
{
    public function index()
    {
        $adresses = DeliveryAddresses::where('user_id', auth()->user()->id)->get();
        $user = auth()->user();
        return view('front.account.adresses')->with('user',$user)->with('adresses',$adresses);
    }

    public function add(){

        return view('front.account.address-form')->with('user',auth()->user())
                                                    ->with('action','store');
    }

    public function store(AddressRequest $request){

        $validator = Validator::make($request->all(),$request->rules());

        if($validator->fails()){

            return back()
                        ->withErrors($validator)
                        ->withInput()->back();

        }

        $validated = $validator->validated();

        $validated['user_id'] = auth()->user()->id;

        DeliveryAddresses::create($validated);


        return redirect()->route('front.account.addresses');
    }

    public function edit($id){

        $address = DeliveryAddresses::where('user_id', auth()->user()->id)->findOrFail($id);

        return view('front.account.address-form', compact('address'))->with('user',auth()->user())
                                                                        ->with('action','update');

    }

    public function update(AddressRequest $request)
    {
        $validator = Validator::make($request->all(),$request->rules());

        if($validator->fails()){

            return back()
                        ->withErrors($validator)
                        ->withInput()->back();

        }

        $validated = $validator->validated();

        $adr = DeliveryAddresses::findOrFail($request->input('id'));
        $adr->update($validated);



        return redirect()->route('front.account.addresses');
    }

    public function destroy($id)
    {
        $address = DeliveryAddresses::where('user_id', auth()->user()->id)->findOrFail($id);

        $address->delete();
        return redirect()->route('front.account.addresses')->with('success', 'L\'adresse a été supprimée!');
    }
}

app/Http/Controllers/Front/Account/BookingController.php
<?php

namespace App\Http\Controllers\Front\Account;

use App\Models\User;
use App\Models\Booking;
use App\Models\Product;
use Illuminate\Support\Str;
use MongoDB\Driver\Session;
use Illuminate\Http\Request;
use App\Models\DeliveryAddresses;
use App\Http\Controllers\Controller;
use App\Notifications\BookingStatusNotification;

class BookingController extends Controller
{

    public function checkout(Request $request)
    {
        //        dd($request,session());
        //        session(['selectedPeriod' => $request->selectedPeriod]);
        //        session(['start_date' => $request->start_date]);
        //        session(['end_date' => $request->end_date]);
        //        session(['price' => $request->price]);

        $selectedPeriod = $request->selectedPeriod;
        $start_date = $request->input_start_date;
        $end_date = $request->input_end_date;
        $price = $request->input_price;
        $product = Product::with(['images', 'category', 'brand'])->findOrFail($request->input_product_id);

        $delivery_addresses = User::find(auth()->user()->id)->deliveryAddresses;

        //redirect('front.account.booking');'


        return view(
            'front.account.checkout',
            compact(['selectedPeriod', 'start_date', 'end_date', 'price', 'product', 'delivery_addresses'])
        );
    }

    public function save(Request $request)
    {
        if ($request->has('delivery_address') && $request->delivery_address != "") {
            $address_id = $request->delivery_address;
        } else {
            $address = DeliveryAddresses::create(
                [
                    'user_id' => auth()->user()->id,
                    'contact_person' => $request->contact_person,
                    'contact_phone' => $request->contact_phone,
                    'address_label' => $request->address_label,
                    'street' => $request->address,
                    'zip_code' => $request->zip_code,
                    'city' => $request->city
                ]);

            $address_id = $address->id;
        }


        $booking = Booking::create(
            [
                'code' => Str::upper(Str::random(5)) . auth()->user()->id,
                'user_id' => auth()->user()->id,
                'delivery_address_id' => $address_id,
                'status_event_id' => 1,
                'start_date' => $request->start_date,
                'end_date' => $request->end_date,
                'price' => $request->price,
                'deposit' => $request->deposit,
                'payment_note' => 'Commande Créé le ' . date('d/m/Y H:i:s'),
            ]);


        //Customer notification
        $notification = $booking->generateStatusNotification();
        $user = $booking->user;
        $user->notify(new BookingStatusNotification($booking));
        session()->put('success_commande', $booking->code);
        return redirect()->route('front.account.order.history');
    }
}

app/Http/Controllers/Front/Account/BookingHistoryController.php
<?php

namespace App\Http\Controllers\Front\Account;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BookingHistoryController extends Controller
{
    //
}

app/Http/Controllers/Front/Account/CheckoutController.php
<?php

namespace App\Http\Controllers\Front\Account;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CheckoutController extends Controller
{
    public function index()
    {
        //
    }

    public function chekout(Request $request)
    {
        session(['selectedPeriod' => $request->selectedPeriod]);
        session(['start_date' => $request->start_date]);
        session(['end_date' => $request->end_date]);
        session(['price' => $request->price]);
        redirect('front.account.booking');
    }
}

app/Http/Controllers/Front/Account/DashboardController.php
<?php

namespace App\Http\Controllers\Front\Account;

use App\Http\Controllers\Front\FrontController;
use App\Models\Booking;

class DashboardController extends FrontController
{
    public function __construct()
    {

    }


    public function index(){
        return view('front.account.dashboard');
    }

    public function profile()
    {
        return view('front.account.profile');
    }

    public function adresses()
    {
        return view('front.account.adresses');
    }

    public function shop()
    {
        return view('front.account.shop');
    }

    public function paymentMethods()
    {
        return view('front.account.payment-methods');
    }

    public function orderHistory()
    {
        $orders = collect(Booking::with('products','currentStatus','deliveryAddress')
            ->where('user_id', auth()->user()->id)
            ->orderBy('id','DESC')
            ->get())->groupBy('status_event_id')->sortKeys();

        return view('front.account.order-history',compact('orders'));
    }
}

app/Http/Controllers/Front/Account/MyShopController.php
<?php

namespace App\Http\Controllers\Front\Account;

use App\Models\Product;
use Illuminate\Http\Request;


use App\Models\SubmitedProduct;
use App\Models\Commission;
use App\Http\Controllers\Front\FrontController;

class MyShopController extends FrontController
{
    // List all submitted products

    public function index(){

        $submittedProducts = SubmitedProduct::where('user_id','=',auth()->user()->id)
                                        ->where('migrated', '==',0)
                                        ->orderBy('id','DESC')
                                        ->with('category','brand','shop_product')
                                        ->get();

        $affectedProducts = Product::where('user_id','=',auth()->user()->id)
            ->orderBy('id','DESC')
            ->with('category','brand')
            ->get();
        $my_products = $submittedProducts->merge($affectedProducts);
        return view('front.account.my-shop',compact('my_products'));
    }

    public function add_product(){

        return view('front.account.shop');

    }

    public function store_product(Request $request){
//dd($request);
    }

    public function delete_product($id){

        SubmitedProduct::where('id','=',$id)->where('user_id','=',auth()->user()->id)->delete();

        return back();
    }

    public function my_commissions()
    {
        $collection = Commission::query();

        $collection->with('user', 'booking')
            ->orderBy('created_at')
            ->where('user_id','=',auth()->user()->id);

        $commissions = $collection->get();

        return view('front.account.commissions',compact('commissions'));

    }
}

app/Http/Controllers/Front/Account/ProfileController.php
<?php

namespace App\Http\Controllers\Front\Account;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\Models\User;
use Illuminate\Http\Request;

class ProfileController extends Controller
{


    public function index()
    {
        $user = auth()->user();
        return view('front.account.profile')->with('user',$user);
    }

    public function update(UserRequest $reuqest)
    {
        $user = User::find(auth()->user()->id);
        $user->update( $reuqest->validated() );

        return view('front.account.profile')
            ->with('user',$user)
            ->with('notification_success','Enregistré avec succès');
    }
}

app/Http/Controllers/Front/FrontController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class FrontController extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Front/HomeController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\AttributeValues;
use App\Models\Product;
use App\Models\Booking;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Models\Category;

class HomeController extends FrontController
{
    public function __construct()
    {

    }

    public function index(){
        $booked = array();
        /* Check if the cart is empty or have alreadu items */
        $cart = session()->get('cart');

        // the cart has already items , get all bookings for that dates
        if ($cart != null && count($cart) > 0) {

            $start_date = session()->get('start_date');
            $end_date = session()->get('end_date');

            $booked = Booking::getBookedProducts($start_date,$end_date);
        }

        $all_sizes = AttributeValues::select('id', 'value')
            ->where('attribute_id',config('app.filters')['size'])
            ->orderBy('value')
            ->get();

        $products = Product::latest()
            ->with(['category','brand','images'])
            ->active()
            ->take(6)->get();
        return view('front.home',[
            'products' => $products,
            'booked' => $booked,
            'all_sizes' => $all_sizes
        ]);
    }


    public function filter(Request $request){
       // dd($request);
        $validated = $request->validate([
            'category' => 'nullable|numeric',
            'size' => 'nullable|numeric',
            'start_date'     => 'nullable'
        ]);

        $category = $validated['category'];
        $start_date = Carbon::parse($validated['start_date'])->format('Y-m-d H:i:s');
//
//        if($start_date){
//            session()->put('start_date', $start_date);
//        }

        $selected_category = null;
        if($category > 0){
            $selected_category = Category::findOrFail($category)->slug;
        }
        return redirect()->route('front.shop',['category'=>$selected_category,'filters[1]'=> $validated['size'], 'date'=> $validated['start_date']]);

    }
}

app/Http/Controllers/Front/PageController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PageController extends Controller
{
    //

    public function leConcept()
    {
        return view('front.le-concept');
    }
    public function faq()
    {
        return view('front.faq');
    }
    public function politique()
    {
        return view('front.politique');
    }
}

resources/views/front/partials/header.blade.php
<header class="bg-light navbar-sticky">
    <div class="navbar navbar-expand-lg navbar-light">
        <div class="container">

            {{-- <a class="navbar-brand d-none d-sm-block flex-shrink-0 me-4 order-lg-1 h5 m-0" href="/"> --}}
            {{-- <span class="text-primary">Easy</span><span class="text-secondary">Dress</span> --}}
            {{-- </a> --}}

            <a class="navbar-brand me-2 order-lg-1" href="/">
                <img src="{{ asset('images/EasyDress-logo.svg') }}" alt="Easy Dress">
            </a>

            <!-- Toolbar-->
            <div class="navbar-toolbar d-flex align-items-center order-lg-3">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                {{-- <a class="navbar-tool d-none d-lg-flex" href="javascript:void(0)" data-toggle="collapse" data-target="#searchBox" role="button" aria-expanded="false" aria-controls="searchBox"> --}}
                {{-- <span class="navbar-tool-tooltip">Search</span> --}}
                {{-- <div class="navbar-tool-icon-box"><i class="fas fa-search"></i></div> --}}
                {{-- </a> --}}
                {{-- <a class="navbar-tool d-none d-lg-flex" href="dashboard-favorites.html"> --}}
                {{-- <span class="navbar-tool-tooltip">Favorites</span> --}}
                {{-- <div class="navbar-tool-icon-box"><i class="fas fa-heart"></i></div> --}}
                {{-- </a> --}}
                <div class="navbar-tool mr-3">
                    <a class="navbar-tool-icon-box bg-secondary dropdown-toggle" href="{{ route('front.showcart') }}">
                        <span class="navbar-tool-label">
                            {{ session()->get('total_items') ?? 0 }}
                        </span>
                        <i class="fas fa-shopping-basket"></i>
                    </a>
                    <a class="navbar-tool-text" href="{{ route('front.showcart') }}"><small>Mon Panier</small> {{ session()->get('total_amount') ?? 0 }} DT</a>
                </div>
                @guest
                    <div class="navbar-tool ml-3">
                        <a class="navbar-tool-icon-box bg-secondary" href="{{ route('login') }}">
                            <i class="fas fa-user"></i>
                        </a>
                        <a class="navbar-tool-text" href="{{ route('front.account.dashboard') }}">
                            <small>Bienvenue,</small>
                            <span class="font-weight-bold uppercase text-primary">Connectez vous</span>
                        </a>
                    </div>
                @endguest
                @auth

                    <div class="navbar-tool dropdown ml-2">

                        <a href="{{ route('front.account.dashboard') }}" class="navbar-tool-icon-box bg-secondary"><i class="fas fa-user"></i></a>
                        <a class="navbar-tool-text" href="{{ route('front.account.dashboard') }}">
                            <small>Bienvenue</small>
                            <span class="font-weight-bold uppercase text-primary">{{ Auth::user()->name }}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end">
                            <div style="min-width: 14rem;">
                                <p class="dropdown-header font-weight-bolder text-uppercase">Mon Compte</p>
                                <a class="dropdown-item d-flex align-items-center"
                                    href="{{ route('front.account.profile') }}"><i class="fas fa-id-card mr-2"></i>Mon
                                    Profil</a>
                                <a class="dropdown-item d-flex align-items-center"
                                    href="{{ route('front.account.addresses') }}"><i
                                        class="fas fa-map-marker-alt mr-2"></i>Mes Adresses</a>
                                <a class="dropdown-item d-flex align-items-center"
                                    href="{{ route('front.account.order.history') }}"><i
                                        class="fas fa-history mr-2"></i>Historique</a>
                                <div class="dropdown-divider"></div>
                                <p class="dropdown-header font-weight-bolder text-uppercase">Ma Boutique</p>

                                <a class="dropdown-item d-flex align-items-center"
                                    href="{{ route('front.account.my-shop') }}"><i class="fas fa-store mr-2"></i> Mes
                                    Dépôt</a>
                                <a class="dropdown-item d-flex align-items-center"
                                    href="{{ route('front.account.my-shop.my-commissions') }}"><i
                                        class="fas fa-money-bill mr-2"></i>Mes Commissions</a>

                                <div class="dropdown-divider"></div>
                                <form method="POST" action="{{ route('logout') }}">
                                    @csrf
                                    <button class="dropdown-item d-flex align-items-center text-danger" type="submit"><i
                                            class="fas fa-sign-out-alt mr-2"></i>Sign Out</button>
                                </form>
                            </div>
                        </div>
                    </div>
                @endauth

            </div>


            <div class="collapse navbar-collapse me-auto order-lg-2" id="navbarCollapse">
                <!-- Search-->
                {{-- <div class="input-group d-lg-none my-3"><i class="ci-search position-absolute top-50 start-0 translate-middle-y text-muted fs-base ms-3"></i> --}}
                {{-- <input class="form-control rounded-start" type="text" placeholder="Search marketplace"> --}}
                {{-- </div> --}}
                <!-- Categories dropdown-->
                <ul class="navbar-nav navbar-mega-nav pr-lg-2 mr-lg-2 ml-lg-3 border-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle font-weight-bolder text-uppercase" href="#"
                            data-toggle="dropdown">Emprunter</a>
                        <div class="dropdown-menu py-1">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="dropdown-header text-uppercase font-weight-bold text-dark">Type de vêtements</div>
                                    <a class="dropdown-item text-uppercase" href="{{ route('front.shop') }}">Voir Tout</a>
                                    @foreach ($allCategories as $category)
                                        <a class="dropdown-item text-uppercase"
                                            href="{{ route('front.shop', $category) }}">{{ $category->name }}</a>
                                    @endforeach
                                </div>
                                <div class="col-md-6 d-none">
                                    <div class="dropdown-header text-uppercase font-weight-bold">Les marques</div>
                                    <a class="dropdown-item text-uppercase" href="{{ route('front.shop') }}">Voir
                                        Tout</a>
                                    @foreach ($allbrands as $brand)
                                        <a class="dropdown-item text-uppercase"
                                            href="{{ route('front.shop', $brand) }}">{{ $brand->name }}</a>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </li>

                    <li class="nav-item"><a href="{{ route('front.account.my-shop.add_product') }}"
                            class="nav-link text-uppercase font-weight-bold">Déposer</a></li>
                    <li class="nav-item"><a href="{{ route('front.le-concept') }}"
                            class="nav-link text-uppercase font-weight-bold">Le Concept</a></li>
                    <li class="nav-item"><a href="{{ route('front.faq') }}"
                            class="nav-link text-uppercase font-weight-bold">faq</a></li>
                </ul>
                <!-- Primary menu-->

            </div>
        </div>
    </div>


    <div class="search-box collapse" id="searchBox">
        <div class="card pt-2 pb-4 border-0 rounded-0">
            <div class="container">
                <div class="input-group"><i
                        class="ci-search position-absolute top-50 start-0 translate-middle-y text-muted fs-base ms-3"></i>
                    <input class="form-control rounded-start" type="text" placeholder="Search marketplace">
                </div>
            </div>
        </div>
    </div>
</header>

resources/views/front/partials/hero-home.blade.php
<section class="hero-home">
    <div class="swiper-container hero-slider dark-overlay">
        <div class="swiper-wrapper">
            <div class="swiper-slide" style="background-image:url({{ asset('images/slide1.jpg') }})"></div>
            <div class="swiper-slide" style="background-image:url({{ asset('images/slide2.jpg') }})"></div>
            <div class="swiper-slide" style="background-image:url({{ asset('images/slide4.jpg') }})"></div>
        </div>
    </div>
    <div class="container py-6 py-md-7 h-100">
        <div class="row justify-content-center align-content-end h-100 pb-100">
            <div class="col-xl-10 mb-5">
                <div class="text-center text-white">
                    <p class="subtitle subtitle-center text-white">JE CHOISIS MA TENUE ET RÉSERVE MA DATE</p>
{{--                    <h1 class="display-3 text-shadow">Location de vêtement</h1>--}}
                </div>
                <div class="search-bar mt-2 bg-white text-left">
                    <form action="{{ route('front.home.filter') }}" method="post">
                        @csrf
                        <div class="container form-container p-lg-0">
                            <div class="row">
                                <div class="col-lg-3 col-md-12 mb-2 mb-lg-0 box box-first px-0 pb-2 pt-2 p-lg-0 ">
                                    <div class="d-flex h-100">
                                        <div class="px-2 pt-1 bg-primary text-white"><i class="fas fa-tshirt"></i></div>
                                        <select class="selectpicker  w-100" id="" title="Type de vêtement" name="category">
                                            @foreach($allCategories as $category)
                                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-6  mb-2 mb-lg-0 box  px-0 pb-2 pb-lg-0">
                                    <div class="d-flex h-100">
                                        <div class="px-2 pt-1 bg-primary text-white"><i class="fas fa-ruler"></i></div>
                                        <select class="selectpicker w-100" name="size" title="La taille">
                                            @foreach($all_sizes as $size)
                                                <option value="{{ $size->id }}">{{ $size->value }}</option>
                                            @endforeach
                                        </select>
                                    </div>

                                </div>
                                <div class="col-lg-3 col-md-6  box box-last  px-0 pb-2 pb-lg-0">
                                    <div class="d-flex h-100">
                                        <div class="px-2 pt-1 bg-primary text-white"><i class="fas fa-calendar"></i></div>
                                        <input type='text' name="start_date"  class="form-control border-0 date-input" data-language='fr' placeholder="Date de début" autocomplete="off" />
                                    </div>
                                </div>
                                <div class="col-lg-3 px-0">
                                    <button class="btn btn-primary btn-block btn-sm h-100 rounded-0" type="submit"> Chercher</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/front/partials/page-header.blade.php
<header class="page-header section-spacing bg-secondary text-white">
    <div class="container text-center">
            <h1 class="mb-0 text-uppercase"> @yield('page-title')</h1>
    </div>
</header>